#!/usr/bin/env bash
#this script displays list of currently running processes
# must show all processes for all users, including those which not have a TTY
# Display a user-oriented format
# also shows process hierarchy

ps -a -x -u -f
