#!/usr/bin/env bash
#displays numbers from 1 to 100
# displays "Fizzbuzz" when number is a multiple of 3 and 5
# displays "Fizz" when number is a multiple of 3
# displays "Buzz" when number is a multiple of 5
# otherwise displays number

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
