#!/usr/bin/env bash
#loops 1 to 10 and displays "bad luck" on 4th iteration, 
#"good luck" on 8th iteration 
#"Best school" for other iterations

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"

	elif [ $count -eq 7 ]
	then
		echo "good luck"

	else
		echo "Best School"
	fi
	(( count++ ))
done
