#!/usr/bin/env bash
#Displays numbers from 1 to 20:
# displays 4 then "bad luck from China" on 4th iteration
# displays 9 then "bad luck from Japan" on 9th iteration
# displays 17 then "bad luck from Italy" on 17th iteration

count=1

while [ $count -le 20 ]
do
	echo $count
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
